export const ADD_SECOND = "ADD_SECOND";

export const SET_TIMER_DURATION = "SET_TIMER_DURATION";

export const START_STOPWATCH = 'START_STOPWATCH';
export const PAUSE_STOPWATCH = 'PAUSE_STOPWATCH';
export const RESTART_STOPWATCH = 'RESTART_STOPWATCH';
export const ADD_SECOND_STOPWATCH = 'ADD_SECOND_STOPWATCH';

export const START_TIMER = 'START_TIMER';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const RESTART_TIMER = 'RESTART_TIMER';
export const ADD_SECOND_TIMER = 'ADD_SECOND_TIMER';